project:
  type: website
  output-dir: "docs"

website:
  title: "Cassie Speakman" 
  navbar:
    background: secondary
    search: false
    right:
      - href: about.qmd
        text: About
#      - href: research.qmd
#        text: Research themes
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks & workshops
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    smooth-scroll: true
    fontsize: 1em

editor: visual

